"use client";

import React, { useState } from "react";

interface VerifierProps {
  isOpen: boolean;
  onClose: () => void;
  certificate: any;
}

export default function CertificateVerifierModal({ isOpen, onClose, certificate }: VerifierProps) {
  const [inputCert, setInputCert] = useState<string>(
    certificate ? JSON.stringify(certificate, null, 2) : ""
  );
  const [verificationResult, setVerificationResult] = useState<{
    is_valid: boolean;
    verdict: string;
    certificate_id: string;
    signature_algorithm: string;
  } | null>(null);
  const [loading, setLoading] = useState(false);

  const handleVerify = async () => {
    setLoading(true);
    setVerificationResult(null);
    try {
      const parsed = JSON.parse(inputCert);
      const res = await fetch("/api/governance/verify-certificate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(parsed)
      });
      if (res.ok) {
        setVerificationResult(await res.json());
      }
    } catch (e) {
      setVerificationResult({
        is_valid: false,
        verdict: "INVALID_JSON_PAYLOAD",
        certificate_id: "N/A",
        signature_algorithm: "N/A"
      });
    } finally {
      setLoading(false);
    }
  };

  const handleTamper = () => {
    try {
      const parsed = JSON.parse(inputCert);
      parsed.topic = "TAMPERED_INJECTED_PROMPT_TOPIC";
      parsed.canonical_payload = "cert:tampered:tampered:999:timestamp";
      setInputCert(JSON.stringify(parsed, null, 2));
      setVerificationResult(null);
    } catch (e) {}
  };

  const handleReset = () => {
    if (certificate) {
      setInputCert(JSON.stringify(certificate, null, 2));
      setVerificationResult(null);
    }
  };

  if (!isOpen) return null;

  return (
    <div style={{
      position: "fixed",
      top: 0, left: 0, right: 0, bottom: 0,
      background: "rgba(0, 0, 0, 0.75)",
      backdropFilter: "blur(12px)",
      zIndex: 9999,
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      padding: "20px"
    }}>
      <div style={{
        background: "#0d0f1a",
        border: "1px solid rgba(16, 185, 129, 0.4)",
        borderRadius: "14px",
        maxWidth: "720px",
        width: "100%",
        maxHeight: "85vh",
        overflowY: "auto",
        padding: "24px",
        color: "var(--ink)"
      }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "16px" }}>
          <h2 style={{ fontSize: "18px", fontWeight: 700, margin: 0, color: "#10b981" }}>
            📜 Cryptographic Compliance Certificate Verifier
          </h2>
          <button
            onClick={onClose}
            style={{ background: "transparent", border: "none", color: "var(--muted)", fontSize: "18px", cursor: "pointer" }}
          >
            ✕
          </button>
        </div>
        <p style={{ fontSize: "13px", color: "var(--muted)", marginBottom: "16px" }}>
          Verify HMAC-SHA256 signatures generated by the AI Safety Authority & IBM watsonx.governance. Test authentic or tampered payloads live.
        </p>

        <textarea
          value={inputCert}
          onChange={(e) => setInputCert(e.target.value)}
          rows={12}
          style={{
            width: "100%",
            fontFamily: "monospace",
            fontSize: "11px",
            background: "#06070c",
            border: "1px solid var(--line)",
            borderRadius: "8px",
            padding: "10px",
            color: "#a7f3d0",
            marginBottom: "14px",
            resize: "vertical"
          }}
        />

        <div style={{ display: "flex", gap: "10px", alignItems: "center", marginBottom: "18px", flexWrap: "wrap" }}>
          <button
            type="button"
            onClick={handleVerify}
            disabled={loading}
            style={{
              padding: "8px 16px",
              background: "#10b981",
              color: "#000",
              fontWeight: 700,
              border: "none",
              borderRadius: "6px",
              cursor: "pointer",
              fontSize: "12px"
            }}
          >
            {loading ? "Verifying..." : "🔐 Verify Cryptographic Signature"}
          </button>
          <button
            type="button"
            onClick={handleTamper}
            style={{
              padding: "8px 14px",
              background: "rgba(239, 68, 68, 0.15)",
              color: "#f87171",
              border: "1px solid rgba(239, 68, 68, 0.4)",
              borderRadius: "6px",
              cursor: "pointer",
              fontSize: "12px",
              fontWeight: 600
            }}
          >
            Inject Tamper Payload
          </button>
          <button
            type="button"
            onClick={handleReset}
            style={{
              padding: "8px 14px",
              background: "rgba(255, 255, 255, 0.05)",
              color: "var(--muted)",
              border: "1px solid var(--line)",
              borderRadius: "6px",
              cursor: "pointer",
              fontSize: "12px"
            }}
          >
            Reset Authentic
          </button>
        </div>

        {verificationResult && (
          <div style={{
            padding: "12px 16px",
            borderRadius: "8px",
            background: verificationResult.is_valid ? "rgba(16, 185, 129, 0.1)" : "rgba(239, 68, 68, 0.15)",
            border: `1px solid ${verificationResult.is_valid ? "#10b981" : "#ef4444"}`,
            fontSize: "13px"
          }}>
            <div style={{ display: "flex", alignItems: "center", gap: "8px", marginBottom: "4px" }}>
              <span style={{ fontSize: "16px" }}>{verificationResult.is_valid ? "✅" : "❌"}</span>
              <strong style={{ color: verificationResult.is_valid ? "#10b981" : "#ef4444" }}>
                {verificationResult.is_valid ? "AUTHENTIC CERTIFICATE VERIFIED" : "SECURITY ALERT: TAMPER DETECTED"}
              </strong>
            </div>
            <p style={{ margin: "2px 0", fontSize: "11px", color: "var(--muted)" }}>
              Algorithm: {verificationResult.signature_algorithm} | Certificate ID: {verificationResult.certificate_id}
            </p>
            <p style={{ margin: "4px 0 0", fontSize: "12px", color: "var(--ink)" }}>
              {verificationResult.is_valid
                ? "All scene prompt hashes, policy limits, and safety audits are cryptographically sealed and untouched."
                : "The canonical signature does not match the payload. Content was modified after certification."}
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
