import os
import pytest
from app.services.video_provider_catalog import VideoProviderCatalog
from app.services.video_gen_service import RealVideoGenService

def test_video_provider_catalog_lists_all_providers():
    providers = VideoProviderCatalog.list_providers()
    provider_ids = [p.id for p in providers]
    assert "mock" in provider_ids
    assert "gemini_omni" in provider_ids
    assert "runway" in provider_ids
    assert "kling" in provider_ids

def test_video_provider_catalog_availability_reason(monkeypatch):
    monkeypatch.delenv("RUNWAYML_API_KEY", raising=False)
    monkeypatch.delenv("RUNWAY_API_KEY", raising=False)
    monkeypatch.delenv("KLING_API_KEY", raising=False)

    providers = VideoProviderCatalog.list_providers()
    runway = next(p for p in providers if p.id == "runway")
    assert not runway.is_available
    assert "Requires RUNWAY_API_KEY in environment" in (runway.disabled_reason or "")

    kling = next(p for p in providers if p.id == "kling")
    assert not kling.is_available
    assert "Requires KLING_API_KEY in environment" in (kling.disabled_reason or "")

    mock_p = next(p for p in providers if p.id == "mock")
    assert mock_p.is_available
    assert mock_p.disabled_reason is None

def test_real_video_gen_service_raises_on_missing_key(monkeypatch):
    monkeypatch.delenv("RUNWAYML_API_KEY", raising=False)
    monkeypatch.delenv("RUNWAY_API_KEY", raising=False)
    svc = RealVideoGenService()

    with pytest.raises(ValueError, match="RUNWAYML_API_KEY is not configured"):
        svc.generate_clip("proj_1", 1, "Cinematic camera move", "runway")

def test_real_video_gen_service_generates_clip_on_configured_key(monkeypatch):
    monkeypatch.setenv("RUNWAY_API_KEY", "real_live_test_key_123")
    svc = RealVideoGenService()
    path = svc.generate_clip("proj_test_runway", 1, "Hyper-realistic drone shot", "runway")
    assert os.path.exists(path)
    with open(path, "rb") as f:
        assert b"MOCK VIDEO DATA GENERATED BY RUNWAY" in f.read()

def test_real_video_gen_service_mock_provider():
    svc = RealVideoGenService()
    path = svc.generate_clip("proj_test_mock", 1, "Simple animation", "mock")
    assert os.path.exists(path)
    with open(path, "rb") as f:
        assert b"MOCK VIDEO DATA GENERATED BY MOCK PROVIDER" in f.read()


def test_video_provider_pipeline_missing_credentials_records_descriptive_error(monkeypatch):
    from fastapi.testclient import TestClient
    from app.main import app
    monkeypatch.delenv("KLING_API_KEY", raising=False)
    client = TestClient(app)

    # Create project requesting unconfigured 'kling' provider
    res = client.post("/api/projects", json={
        "topic": "Volcanic Eruption",
        "duration_seconds": 10,
        "tts_provider": "mock",
        "video_provider": "kling"
    })
    assert res.status_code == 200
    proj_id = res.json()["id"]

    # Generate and approve prompt
    client.post(f"/api/projects/{proj_id}/prompts/next")
    client.post(f"/api/projects/{proj_id}/prompts/1/approve", json={"actor": "director"})

    # Submit production
    prod_resp = client.post(f"/api/projects/{proj_id}/scenes/1/production")
    assert prod_resp.status_code == 200

    # Retrieve jobs and verify descriptive error is surfaced without unhandled 500
    jobs_resp = client.get(f"/api/projects/{proj_id}/production-jobs")
    assert jobs_resp.status_code == 200
    jobs = jobs_resp.json()
    assert len(jobs) == 1
    assert jobs[0]["status"] == "FAILED_PERMANENT"
    assert "KLING_API_KEY is not configured in environment variables" in jobs[0]["error"]

