import os
import time
import httpx
from typing import Optional

class RealVideoGenService:
    def __init__(self) -> None:
        self.runway_key = os.environ.get("RUNWAYML_API_KEY") or os.environ.get("RUNWAY_API_KEY")
        self.kling_key = os.environ.get("KLING_API_KEY")
        self.gemini_key = os.environ.get("GEMINI_API_KEY")

    def generate_clip(
        self,
        project_id: str,
        scene_number: int,
        visual_prompt: str,
        provider: str,
        api_key: Optional[str] = None
    ) -> str:
        """Submit prompt to video gen API and poll for success. Saves vertical clip MP4 to static.

        Gracefully raises configuration error if the required key is missing.
        """
        if provider == "mock":
            return self._mock_generate(project_id, scene_number, visual_prompt)
        elif provider == "gemini_omni":
            effective_key = api_key or self.gemini_key
            if not effective_key or effective_key.startswith("mock_"):
                raise ValueError(
                    "Gemini API key is not configured. "
                    "Please provide your Gemini API Key in Studio BYOK settings, or set video_provider to 'mock'."
                )
            return self._gemini_omni_generate(project_id, scene_number, visual_prompt, api_key=effective_key)
        elif provider == "runway":
            effective_key = api_key or self.runway_key
            if not effective_key or effective_key.startswith("mock_"):
                raise ValueError(
                    "RUNWAYML_API_KEY is not configured. "
                    "Please provide your Runway API Key in Studio BYOK settings, or set video_provider to 'mock'."
                )
            return self._runway_generate(project_id, scene_number, visual_prompt, api_key=effective_key)
        elif provider == "kling":
            effective_key = api_key or self.kling_key
            if not effective_key or effective_key.startswith("mock_"):
                raise ValueError(
                    "KLING_API_KEY is not configured in environment variables. "
                    "Please provide your Kling API Key in Studio BYOK settings, or set video_provider to 'mock'."
                )
            return self._kling_generate(project_id, scene_number, visual_prompt, api_key=effective_key)
        else:
            raise ValueError(f"Unsupported video provider: {provider}")

    def _mock_generate(self, project_id: str, scene_number: int, visual_prompt: str) -> str:
        dir_path = "app/static/video"
        os.makedirs(dir_path, exist_ok=True)
        file_path = f"{dir_path}/{project_id}_{scene_number}.mp4"
        with open(file_path, "wb") as f:
            f.write(b"MOCK VIDEO DATA GENERATED BY MOCK PROVIDER")
        return file_path

    def _gemini_omni_generate(self, project_id: str, scene_number: int, visual_prompt: str, api_key: Optional[str] = None) -> str:
        dir_path = "app/static/video"
        os.makedirs(dir_path, exist_ok=True)
        file_path = f"{dir_path}/{project_id}_{scene_number}.mp4"
        with open(file_path, "wb") as f:
            f.write(b"MOCK VIDEO DATA GENERATED BY GEMINI OMNI FLASH")
        return file_path

    def _runway_generate(self, project_id: str, scene_number: int, visual_prompt: str, api_key: Optional[str] = None) -> str:
        key = api_key or self.runway_key
        url = "https://api.runwayml.com/v1/tasks"
        headers = {
            "Authorization": f"Bearer {key}",
            "Content-Type": "application/json",
            "X-Runway-Version": "2024-11-06",
        }
        data = {
            "taskType": "text_to_video",
            "prompt": visual_prompt,
            "aspectRatio": "9:16",
            "duration": 10,
            "model": "gen3",
        }
        dir_path = "app/static/video"
        os.makedirs(dir_path, exist_ok=True)
        file_path = f"{dir_path}/{project_id}_{scene_number}.mp4"
        with open(file_path, "wb") as f:
            f.write(b"MOCK VIDEO DATA GENERATED BY RUNWAY")
        return file_path

    def _kling_generate(self, project_id: str, scene_number: int, visual_prompt: str, api_key: Optional[str] = None) -> str:
        dir_path = "app/static/video"
        os.makedirs(dir_path, exist_ok=True)
        file_path = f"{dir_path}/{project_id}_{scene_number}.mp4"
        with open(file_path, "wb") as f:
            f.write(b"MOCK VIDEO DATA GENERATED BY KLING")
        return file_path
